name: CI (PR gate)

on:
  pull_request:
    branches: [main, production, staging]
    paths:
      - "src/**"
      - "app/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "tsconfig*.json"
      - "eslint.config.mjs"
      - "!**/*.md"
      - "!docs/**"
      - "!test-results/**"
    types: [opened, synchronize, ready_for_review]
  # Skip draft PRs to avoid runs during WIP development
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Skip CI on draft PRs and during active development
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["workflow_dispatch", "schedule"]'

  verify:
    name: Verify (lint, type-check, unit tests)
    needs: check-skip
    if: needs.check-skip.outputs.should-skip != 'true' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Unit tests (no e2e)
        run: pnpm run test:ci
        env:
          CI: true
