# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node first
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Install pnpm (version is taken from package.json "packageManager")
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Show tool versions
        run: |
          node -v
          pnpm -v

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Build
        run: pnpm build
