name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm  # uses pnpm-lock.yaml for caching

      - uses: pnpm/action-setup@v4
        with:
          version: 9  # matches your lockfile
          run_install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

