name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NEXT_PUBLIC_APP_NAME: "Halbon SaaS Template"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/halbonsaas_ci?schema=public"
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      # 🔑 Install/activate pnpm BEFORE any 'pnpm' commands
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          # optional: run_install: true
      # (optional extra safety on fresh images)
      - name: Enable Corepack (safety)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Build
        run: pnpm build
