name: Automation - PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  sync-labels:
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Sync repository labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0 renovate: datasource=github-releases depName=actions/labeler
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Apply labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0 renovate: datasource=github-releases depName=actions/labeler
        with:
          configuration-path: .github/labeler.yml
          # Never create labels during PR triage; creation happens on push to main
          sync-labels: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
