name: Automation - PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: actions/labeler@5c7539237c7e53ce5c1fd9d9fed3ef7517653242 # v5.0.0 renovate: datasource=github-releases depName=actions/labeler
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
