name: Automation - Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@c9b467466a1b998f241af29356c2ec13c1a96489 # v6.1.0 renovate: datasource=github-releases depName=release-drafter/release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
