name: Security - SCA (Deps Only)

on:
  push:
    branches: [ main ]
    paths:
      - package.json
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]
    paths:
      - package.json
      - pnpm-lock.yaml
  workflow_dispatch: {}

concurrency:
  group: sca-deps-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  trivy-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TRIVY_CACHE_DIR: .trivycache
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0 renovate: datasource=github-releases depName=actions/checkout
      - name: Cache Trivy DB
        uses: actions/cache@v4 # renovate: datasource=github-releases depName=actions/cache
        with:
          path: | 
            .trivycache
          key: ${{ runner.os }}-trivy-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-trivy-
      - name: Install Trivy
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-releases depName=aquasecurity/trivy-action
      - name: Scan lockfile (SARIF)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-releases depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: pnpm-lock.yaml
          format: sarif
          output: trivy-deps-lockfile.sarif
          severity: HIGH,CRITICAL
          exit-code: '0'
          ignore-unfixed: true
      - name: Upload SARIF (lockfile)
        if: always()
        uses: github/codeql-action/upload-sarif@v3 # renovate: datasource=github-releases depName=github/codeql-action
        with:
          sarif_file: trivy-deps-lockfile.sarif
          category: trivy-deps-lockfile
      - name: Scan lockfile (table, fail on HIGH+)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-releases depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: pnpm-lock.yaml
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true
      - name: Scan manifest (SARIF)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-releases depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: package.json
          format: sarif
          output: trivy-deps-manifest.sarif
          severity: HIGH,CRITICAL
          exit-code: '0'
          ignore-unfixed: true
      - name: Upload SARIF (manifest)
        if: always()
        uses: github/codeql-action/upload-sarif@v3 # renovate: datasource=github-releases depName=github/codeql-action
        with:
          sarif_file: trivy-deps-manifest.sarif
          category: trivy-deps-manifest
      - name: Scan manifest (table, fail on HIGH+)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-releases depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: package.json
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true
