name: Security - SCA

on:
  push:
    branches: [ main ]
    paths:
      - package.json
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]
    paths:
      - package.json
      - pnpm-lock.yaml
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch: {}

concurrency:
  group: security-sca-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  deps:
    name: Deps-only scan
    if: >-
      github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TRIVY_CACHE_DIR: .trivycache
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0 renovate: datasource=github-releases depName=actions/checkout
      - name: Cache Trivy DB
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4 renovate: datasource=github-releases depName=actions/cache
        with:
          path: |
            .trivycache
          key: ${{ runner.os }}-trivy-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-trivy-
      - name: Scan lockfile (SARIF)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: pnpm-lock.yaml
          format: sarif
          output: trivy-deps-lockfile.sarif
          severity: HIGH,CRITICAL
          exit-code: '0'
          ignore-unfixed: true
      - name: Upload SARIF (lockfile)
        if: always()
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11 renovate: datasource=github-releases depName=github/codeql-action
        with:
          sarif_file: trivy-deps-lockfile.sarif
          category: trivy-deps-lockfile
      - name: Scan manifest (SARIF)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: package.json
          format: sarif
          output: trivy-deps-manifest.sarif
          severity: HIGH,CRITICAL
          exit-code: '0'
          ignore-unfixed: true
      - name: Upload SARIF (manifest)
        if: always()
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11 renovate: datasource=github-releases depName=github/codeql-action
        with:
          sarif_file: trivy-deps-manifest.sarif
          category: trivy-deps-manifest
      - name: Scan lockfile (table)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: pnpm-lock.yaml
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true
      - name: Scan manifest (table)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: package.json
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true

  weekly:
    name: Full repo weekly scan
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TRIVY_CACHE_DIR: .trivycache
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0 renovate: datasource=github-releases depName=actions/checkout
      - name: Cache Trivy DB
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4 renovate: datasource=github-releases depName=actions/cache
        with:
          path: |
            .trivycache
          key: ${{ runner.os }}-trivy-full-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-trivy-full-
      - name: Run full filesystem scan (SARIF)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-full.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          ignore-unfixed: true
          timeout: '15m'
          skip-files: |
            **/.next/**
            **/node_modules/**
            **/coverage/**
            **/.turbo/**
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11 renovate: datasource=github-releases depName=github/codeql-action
        with:
          sarif_file: trivy-full.sarif
          category: trivy-full
      - name: Run full filesystem scan (table)
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0 renovate: datasource=github-tags depName=aquasecurity/trivy-action
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true
          timeout: '15m'
          skip-files: |
            **/.next/**
            **/node_modules/**
            **/coverage/**
            **/.turbo/**
